org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod
mod_id=politeshop
mod_name=PolitEmpire Donate
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=ru.politempire.politeshop
mod_authors=PolitEmpire
mod_description=Внутриигровое донат-меню, корзина и валюта DC с интеграцией сайта PolitEmpire.

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
neo_version_range=[21.1.0,)
loader_version_range=[4,)
